### PR TITLE
fix: Prevents RTP stream corruption.

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Comment by bbaldino** [comment]
interested to hear about what the bug was here.  something with the seen frame allocator?

**Comment by gpolitis** [comment]
The packet rewrite thread uses SeenFrames to rewrite RTP packets. The translator thread creates/updates/recycles SeenFrames. It is possible for a SeenFrame to be returned (by the translator thread) to the allocator for re-use, while it's being used by the packet rewrite thread. This happens extremely rarely, but it can happen.

**Comment by gpolitis** [comment]
The "major" fix is disabling the lipsync hack by default because it occasionally injects packets that are not re-written..

**Comment by gpolitis** [comment]
And also bumping the seen frame history size.

**Pull request merged**
