### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by pierreozoux**
depends on #434 
related to https://github.com/jitsi/jitsi-meet/pull/1423

### CODE REVIEW

**Comment by gpolitis** [comment]
I personally wouldn't want the docker support inside the jvb repo, I think it should be in a separate repo, like jitsi-videobridge-contrib or docker-jitsi-videobridge.

**Comment by gpolitis** [comment]
I hope this is not misunderstood, I am enthusiast about having docker support and thank you very much @pierreozoux for doing the work.

**Comment by pierreozoux** [comment]
@gpolitis I totally agree, and actually, I wanted to ask you that as the next step for official docker image.

Closing in favor of https://github.com/jitsi/jitsi-meet/issues/1388

**Comment by jitsi-developers** [comment]
@pierreozoux, I wait to help in make a project with focus in a docker for
jitsi. I already have one docker image for jisti that I use, but to have a
official, helping in get a better image, is better for me.

For this goal, I agree with @gpolitis with a new repo at github, with focus
in docker, specially some images like jvb in self, a hammer image, a jibri
and all ecossystem around the jvb.

What you think?

Regards,
Claudio Ferreira

2017-03-28 5:24 GMT-03:00 Pierre Ozoux <notifications@github.com>:

**Pull request closed without merging**
