### PR TITLE
+ Env variable that defines GC type

### PR DESCRIPTION
**Pull request by sych74**
Enable definition of garbage collection via a dedicated env variable VIDEOBRIDGE_GC_TYPE

### CODE REVIEW

**Comment by bgrozev** [comment]
jenkins please test this please

**Comment by sych74** [comment]
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

ICLA has been signed

**Comment by bgrozev** [comment]
Thanks for the contribution!

**Comment by sych74** [comment]
When this improvement will be included into docker image?

**Comment by saghul** [comment]
You should already be able to test it by building the images yourself from the "unstable" repo.

**Pull request merged**
