### PR TITLE
added possibility to generate unique source (SSRC) for channel

### PR DESCRIPTION
**Pull request by sidorovis**
added generate_sources boolean parameter as channel setting - so jitsi videobridge will generate unique SSRC for it

### CODE REVIEW

**Comment by sidorovis** [comment]
I don't have Attlasian code and don't plan to use it.

**Comment by gpolitis** [comment]
Hi @sidorovis, could you please help us understand what are you trying to achieve with this? i.e. why do you need to generate unique ssrcs for the video channel.

**Comment by sidorovis** [comment]
@gpolitis we had case when we can't define SSRC on client side, because amount of users in  conference is not predefined. So users could connect to conference without any SSRC and receive that from conference server side.

**Comment by gpolitis** [comment]
I think I would prefer to see this functionality in the signaling server (for example, Jicofo).

**Pull request closed without merging**
