### PR TITLE
Update bcprov-jdk15on to 1.54

### PR DESCRIPTION
**Pull request by champtar**
Quickly run tested with Firefox Nightly 46 and Chrome 47

Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

### CODE REVIEW

**Comment by lyubomir** [comment]
Jenkins: it's ok to test.

**Comment by ibauersachs** [comment]
Note: this would be obsoleted by https://github.com/jitsi/jitsi-universe/pull/5

**Comment by lyubomir** [comment]
Oh, thank you very much, @ibauersachs! Are you saying that I should merge your PR, then close this one, and remove the bouncycastle dependency from jitsi-videobridge?

**Comment by ibauersachs** [comment]
@lyubomir Please do in the following order:
1) merge the ice4j PRs. If that is done, I'll publish ice4j 1.0 on Maven Central.
2) merge jitsi-universe#5
3) set ice4j to version 1.0 in jitsi-universe (I can create a follow-up PR for that)
4) update the pinned version of jitsi-universe in videobridge and remove the BouncyCastle version (not the dependency).
5) Do the same as in 4 for jicofo, maybe jigasi (haven't looked at that)

**Comment by lyubomir** [comment]
Thank you, @ibauersachs! I'll try to do as you said.

**Comment by ibauersachs** [comment]
@lyubomir Thanks! I updated the comment before to include libjitsi updates.

**Pull request merged**
