### PR TITLE
slight rework to LastNController to make it easier to override its

### PR DESCRIPTION
**Pull request by brianh5**
behavior.

idea here is to tweak a couple things to make it easier to override the specific logic of determining which endpoints should be in last-n (we do some different things here, so have a custom HighfiveLastNController to implement the logic we need).

### CODE REVIEW

**Comment by brianh5** [comment]
cc @bgrozev

**Comment by bgrozev** [comment]
Jenkins test again please

**Comment by bgrozev** [comment]
LGTM, will wait for the tests to run again.

**Comment by damencho** [comment]
Jenkins, test this please

**Comment by bgrozev** [comment]
jenkins test this please

**Comment by bgrozev** [comment]
@brianh5 looking at the base determineLastNList method, it's parameter is unused. Do you use the parameter in your extended implementation, or can we remove it?

**Comment by brianh5** [comment]
@bgrozev yeah i do use it.  memory is a bit fuzzy, but i think since we drive new last-n changes on new endpoints joining (to fill without activity if we have empty slots), there are times where an endpoint is on the new endpoints list, but isn't in conferenceSpeechActivityEndpoints

**Comment by bgrozev** [comment]
Thanks, that makes sense.

**Pull request merged**
