### PR TITLE
add handling in the rest api for header extensions field

### PR DESCRIPTION
**Pull request by brianh5**
REST api is missing a few features compared to the xmpp api, not sure if there's a bigger update in the works but I added support for header extensions here.

### CODE REVIEW

**Comment by brianh5** [comment]
Oops, realized this included more than I had planned.  I'll try and get it cleaned up.

**Comment by bgrozev** [comment]
Hi Brian,

Thank you for your contribution. The RTP header extensions support for REST is something that we'd like to merge. Before we can do that we need you to sign our contributor agreement as either an [individual](https://jitsi.org/icla) or a [corporation](https://jitsi.org/ccla).
Also, there are a couple of minor changes necessary for the code, so that it follows our style guide: opening braces should be on new lines, a Logger instance should be used instead of System.err for logging errors.

Thanks again,
Boris

**Comment by brianh5** [comment]
Cool! Thanks Boris.  I'll work on getting this cleaned up.

**Comment by brianh5** [comment]
Hey Boris, still figuring out the contract piece, but I've tried to make the appropriate style changes here to be consistent with the rest of the file.

**Comment by brianh5** [comment]
@bgrozev just got the contributor agreement signed and submitted

**Comment by brianh5** [comment]
@bgrozev let me know if there's anything else you need from me on this.

**Comment by bgrozev** [comment]
Sorry, Brian, it's been a busy couple of days. I'll review and merge when I get a chance.

**Comment by jitsi-developers** [comment]
Sure, no problem!  Wanted to make sure everything with the contributor
agreement was right.

**Comment by markreg** [comment]
@brianh5 are you able to specify rtcp-fb: ccm fir, nack pli, and goog-remb via the rest api?

**Comment by brianh5** [comment]
@markreg yes, we're able to set that.  i do notice, however, that when you access the conference state via the rest api, that information will not show up.  it looks like RtpChannel::describe (which serializes the bridge data into json to respond to rest requests) only does the ssrc--so if you're worried your rtcp-fb information isn't showing up in rest, i think that's why.

**Comment by bgrozev** [comment]
Videobridge currently doesn't use any of the rtcp-fb fields. It doesn't even store the information, which is why it doesn't show up in replies (either XMPP or REST)

**Comment by markreg** [comment]
So, is it not used because its features are implicit in Videobridge or are the rtcp-fb features seen as unnecessary?

**Comment by markreg** [comment]
Would you accept a pull request with rtcp-fb support?

**Comment by bgrozev** [comment]
Do you mean rtcp-fb support in COLIBRI and the REST interface, or somehow handling the specific rtcp-fb extensions set on a channel? I think we would accept the first, since we can use it to detect FIR, NACK, REMB support for endpoints.
Do you have a specific use-case where you need this?

**Pull request merged**
