### PR TITLE
feat: Implements different strategies for

### PR DESCRIPTION
**Pull request by bgrozev**
selecting the candidate pairs to be kept alive.

### CODE REVIEW

**Comment by bgrozev** [comment]
This is awesome. The tests failed, because jitsi-meet-torture couldn't force the browser to disconnect by blocking it's UDP port :)

**Comment by gpolitis** [comment]
Nice, @bgrozev 👍

**Comment by bgrozev** [comment]
Jenkins on to test

**Comment by bgrozev** [comment]
ok to test

**Comment by bbaldino** [comment]
lgtm

**Pull request merged**
