### PR TITLE
adapt to change in AbstractJettyBundleActivator

### PR DESCRIPTION
**Pull request by bbaldino**
See https://github.com/jitsi/jicoco/pull/99

### CODE REVIEW

**Comment by JonathanLennox** [comment]
Do you want to update the docs to reference the new config syntax?

**Comment by JonathanLennox** [comment]
Also I think this will need the corresponding jicofo change in order for the PR tests to pass.

**Comment by bbaldino** [comment]
> Also I think this will need the corresponding jicofo change in order for the PR tests to pass.

Yeah I ended up adding a backwards-compatible constructor to AbstractJettyBundleActivator

**Comment by bbaldino** [comment]
> Also I think this will need the corresponding jicofo change in order for the PR tests to pass.

I think I will wait on that until more of these are ported over.  The old values will still work.

**Comment by JonathanLennox** [comment]
The backward-compatible constructor isn't sufficient to get jicofo to compile -- because you removed `AbstractJettyBundleActivator.getDefaultPort()` and 'getDefaultTlsPort()`, the overrides in `AuthBundleActivator` are no longer overrides and the compiler errors out.

**Comment by bbaldino** [comment]
> The backward-compatible constructor isn't sufficient to get jicofo to compile -- because you removed `AbstractJettyBundleActivator.getDefaultPort()` and `getDefaultTlsPort()`, the overrides in `AuthBundleActivator` are no longer overrides and the compiler errors out.

Hmph, ok I guess I'll update Jicofo too then.

**Comment by bbaldino** [comment]
jenkins, test this please

**Pull request merged**
