### PR TITLE
Fixes signaling of ungrouped SSRCs

### PR DESCRIPTION
**Pull request by bgrozev**
Fixes a problem with video coming from firefox being dropped.

### CODE REVIEW

**Comment by gpolitis** [comment]
Does this fix 1-1 calls between FF-Chrome that go through the JVB?

**Comment by bgrozev** [comment]
Yes. I haven't tested, but I think it isn't limited to 1-1 (we would never forward anything coming from firefox)

**Comment by bbaldino** [comment]
thanks for finding my mistake, @bgrozev :) i'll merge this...but want to add a unit test for this scenario first so i'll probably copy your branch and add that to merge it.

**Comment by bbaldino** [comment]
boris is out and i don't have perms on his repo, so cloned this branch and added a unit test here: https://github.com/jitsi/jitsi-videobridge/pull/591.

**Pull request closed without merging**
