### PR TITLE
Add checkstyle rules to match guidelines for opening braces.

### PR DESCRIPTION
**Pull request by alexcsf**
According to [Jitsi's Contributing Guidelines](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-contributing/#formatting), for Java:

> Opening braces MUST be on their own line (especially those beginning a method).

I believe this covers all cases.

To avoid reformatting one-line statements in IDEA, there's a few options under:
Settings > Editor > Code Style > Java > Wrapping and Braces > Keep when reformatting

### CODE REVIEW

**Comment by bgrozev** [comment]
Looks like the new check is working as expected :)

**Comment by alexcsf** [comment]
It does seem like it. Should I reformat the failing lines and commit, or do you just want to keep it in mind for some other time?

**Comment by bgrozev** [comment]
Yes, reformat please, there's not a lot of them

**Comment by alexcsf** [comment]
I've applied it to the jvb module, I can do it for the others if you'd like.

**Review by bgrozev — APPROVED** [review]

**Pull request merged**
