### PR TITLE
Add web socket support to rest api

### PR DESCRIPTION
**Pull request by lluczo**

### CODE REVIEW

**Comment by bgrozev** [comment]
Jenkins, please test this please

**Comment by bgrozev** [comment]
LGTM. Have you signed the CLA? I can not find an individual CLA for you, perhaps it's part of a corporate one (if so, please let me know which one).

**Comment by lluczo** [comment]
Hi, I have already signed CLA part of LogMeIn, Inc.

**Comment by bgrozev** [comment]
Thank you!

**Pull request merged**
