### PR TITLE
Fix typo in systemd unit

### PR DESCRIPTION
**Pull request by licaon-kter**
...else component won't register to the XMPP server (at least on ejabberd)

### CODE REVIEW

**Comment by damencho** [comment]
@licaon-kter This was a fix contributed by the community and was tested on several different OS versions.
https://github.com/jitsi/jitsi-videobridge/issues/731

What is your OS and version you are seeing this problem?

**Comment by licaon-kter** [comment]
Debian Buster arm64, DEBs generated with your scripts.

**Comment by damencho** [comment]
We do not do debs.

**Comment by licaon-kter** [comment]
Who is "we"?

What is this for: https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ ?

Why is this here: https://github.com/jitsi/jitsi-videobridge/blob/master/resources/build_deb_package.sh ?

Are we lost in translation?

Anyway from [here](https://www.freedesktop.org/software/systemd/man/systemd.service.html): `To pass a literal dollar sign, use "$$". Variables whose value is not known at expansion time are treated as empty strings. Note that the first argument (i.e. the program to execute) may not be a variable.`

So `$${JVB_HOST:-localhost}` would be what exactly?

**Comment by damencho** [comment]
> Who is "we"?

The jitsi team.



> So `$${JVB_HOST:-localhost}` would be what exactly?

If there is no JVB_HOST set, it will use localhost as value.

**Comment by damencho** [comment]
> Why is this here: https://github.com/jitsi/jitsi-videobridge/blob/master/resources/build_deb_package.sh ?

This is how we build a binary package. We do not do debian source packages.

**Comment by licaon-kter** [comment]
Yes, I've retested with empty, localhost and actual host and they all work now.

Strange that it didn't when I setup it, maybe there was some other change that I did at the same time.

Sorry for the noise.

> This is how we build a binary package. We do not do debian source packages.

I didn't say that...

**Pull request closed without merging**
