### PR TITLE
attempts to fix the npe spam issue that breaks the media flow by removing the weakref

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Comment by bgrozev** [comment]
We should definitely remove the weak reference!

I wonder if looping over all endpoints and their tracks has a performance impact. If I understand correctly this code executes every 15ms, which is quite often. We could keep a regular reference to the source track in `AdaptiveTrackProjection`. A `MediaStreamTrackDesc` doesn't reference anything external, so this would be safe.

**Comment by gpolitis** [comment]
> I wonder if looping over all endpoints and their tracks has a performance impact. If I understand correctly this code executes every 15ms, which is quite often. 

yes, I agree that we should optimize this; the simplest thing we could do is have it run less often but we risk breaking probing or cause issues by stressing the link (with a stale padding estimate that is too high).

Do you have any ideas that you'd like me to incorporate in this PR or can we leave this as a future step? (Note that what I'm changing here has the same space/time complexity as the previous code: the previous version had a loop over the track projections whereas now we have a loop over the endpoints, but the number of track projections that we have is equal to the number of endpoints).

**Comment by gpolitis** [comment]
> We could keep a regular reference to the source track in AdaptiveTrackProjection.

I don't feel super confortable about having egress objects strongly referencing ingress objects and vice versa as it could lead to issues in the future, but today there's no risk as you point out so we could do it this way.

**Comment by JonathanLennox** [comment]
@gpolitis : can you do a YourKit profile of a bridge with your patch, to see if the loop over all the endpoints has a significant performance cost? I don't want to spend effort optimizing it or breaking architectural assumptions before we know that it's actually a problem.

**Comment by JonathanLennox** [comment]
I did a YourKit profile on this code, and the performance impact of this seems negligible -- as in, it's so small it's hard to even find, and click on, the column represented by this new code.

So I don't think we need to worry about the performance of George's current PR.

**Comment by JonathanLennox** [comment]
Screen Shot 2020-02-11 at 1 57 49 PM

**Pull request merged**
