### PR TITLE
fix: Takes into account empty conferences for graceful shutdown.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by gpolitis** [comment]
Just passing by, we've solved the conferences of size 1 problem, right?

**Comment by bgrozev** [comment]
> Just passing by, we've solved the conferences of size 1 problem, right?

What's that problem?

**Comment by gpolitis** [comment]
Thank you for explaining the context of this PR (offline). LGTM.

**Comment by bgrozev** [comment]
Yeah, I think we've solved the size 1 problem, or mostly solved it. Even if not, conferences should eventually drop to size 0 (even if the conference expire thread stop working, resulting in accumulating conferences with size 0).

**Pull request merged**
