### PR TITLE
Fixe for issue https://github.com/jitsi/jitsi-videobridge/issues/279

### PR DESCRIPTION
**Pull request by sarumjanuch**
Guys, i am absolutely new to Java, this pull request is just a reference to what i was talking about in issue that i have opened: https://github.com/jitsi/jitsi-videobridge/issues/279. Please feel free to modify as needed.

### CODE REVIEW

**Comment by bgrozev** [comment]
Hey @sarumjanuch, thank you for the contribution! This looks like a valid fix for an issue that we've had for a long time, but right now the PR seems incomplete. Can you please do the following:
1. Instead of creating a new getTransportManager() add a parameter to the existing getTransportManager(String, boolean) (and remove the FIXME)
2. getTransportManager(String) should pass some value, with a comment that it is unused when create=false
3. Use the parsed value of the 'initiator' field in Videobridge.java (lines 928 and 1070). In both places the value is available in the 'initiator' variable, assume "true" if it is null.
4. Sign our CLA as jenkins requested (or let me know how to find it, I don't currently see it in the list)

**Comment by bgrozev** [comment]
Jenkins, add to whitelist.

**Comment by sarumjanuch** [comment]
Made changes, as you requested. Also did sign CLA, please confirm, that you have received it, or ping me at eugene@thirdlane.com I will send PDF to you.

**Comment by bgrozev** [comment]
Thank you!

**Pull request merged**
