### PR TITLE
mvn: Updates ice4j.

### PR DESCRIPTION
**Pull request by damencho**
Fixes leak of file descriptors.

### CODE REVIEW

**Comment by dbareiro** [comment]
Hi, George/Damian.

This is an additional new fix to those already found in the testing repo for the "too many open files" issue?

Kind regards,
Daniel

**Comment by damencho** [comment]
Yes, that's correct.

**Comment by dbareiro** [comment]
Thanks for confirming, Damian.

Eight days ago I'm using testing and for now I have not had this issue again. Is this a new scenario that can lead to a leak? Is there any other open issue in relation to this new fix? Maybe the issue 1390 for jitsi-meet?

I understand that after several automatic tests, this would have to be automatically integrated into testing repo, right? If so, when you think this could happen?

Kind regards,
Daniel

**Comment by dbareiro** [comment]
Hi, Damian.

> A user reported that he was still seeing issues after we had several fixes on the subject and we 
> managed to reproduce and fix it. Yes, the communication on the subject is in jitsi/jitsi-meet#1390.

Thanks for confirm.

> Not sure what is failing in performance testing and why it is not going to testing. Will check
> later today.

Thank you very much. If you can tell us here when the performance testing have passed to have this in the testing repo, it would be great.

Thanks again.

Kind regards,
Daniel

**Pull request merged**
