### PR TITLE
Added mute video moderation feature

### PR DESCRIPTION
**Pull request by skolmer**
This change adds the ability for a moderator to deactivate the camera of other participants. The implementation uses the same approach that was implemented to mute audio of other participants.

This feature consists of multiple PRs:
- https://github.com/jitsi/jitsi-media-transform/pull/329
- https://github.com/jitsi/jitsi-videobridge/pull/1570
- https://github.com/jitsi/jitsi-xmpp-extensions/pull/37
- https://github.com/jitsi/jicofo/pull/695
- https://github.com/jitsi/lib-jitsi-meet/pull/1496
- https://github.com/jitsi/jitsi-meet/pull/8630

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by bbaldino** [comment]
This looks good...the JMT PR is now merged so you can update the JMT version in the pom here once it publishes.

**Comment by damencho** [comment]
jitsi-media-transform 1.0-218-gd20f452

**Review by bbaldino — APPROVED** [review]

**Comment by bbaldino** [comment]
jenkins, test this please

**Pull request merged**
