### PR TITLE
feat: Log the jvb version on startup.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by damencho** [comment]
Do we still print and the config?

**Review by JonathanLennox — APPROVED** [review]

**Comment by bgrozev** [comment]
> Do we still print and the config?

What do you mean? Here's a snippet from this running locally:

```
2021-05-18 09:32:31.495 INFO: [1] JitsiConfig.<clinit>#47: Initialized newConfig: merge of /xxx/jvb.conf: 1,application.conf @ file:/xxx/jitsi-videobridge/jvb/target/classes/application.conf: 1,system properties,reference.conf @ file:/xxx/jitsi-videobridge/jvb/target/classes/reference.conf: 1,reference.conf @ jar:file:/xxx/.m2/repository/org/jitsi/jitsi-media-transform/1.0-236-g57d193a/jitsi-media-transform-1.0-236-g57d193a.jar!/reference.conf: 1,reference.conf @ jar:file:/xxx/.m2/repository/org/jitsi/ice4j/3.0-25-g5a299cd/ice4j-3.0-25-g5a299cd.jar!/reference.conf: 1
2021-05-18 09:32:31.500 INFO: [1] ReadOnlyConfigurationService.reloadConfiguration#51: loading config file at path /xxx/sip-communicator.properties
2021-05-18 09:32:31.500 INFO: [1] ReadOnlyConfigurationService.reloadConfiguration#56: Error loading config file: java.io.FileNotFoundException: /xxx/sip-communicator.properties (No such file or directory)
2021-05-18 09:32:31.501 INFO: [1] JitsiConfig.<clinit>#68: Initialized legacyConfig: sip communicator props (no description provided)
2021-05-18 09:32:31.503 INFO: [1] JitsiConfig$Companion.reloadNewConfig#94: Reloading the Typesafe config source (previously reloaded 0 times).
2021-05-18 09:32:31.530 INFO: [1] MainKt.main#81: Starting jitsi-videobridge version 2.1
2021-05-18 09:32:31.895 INFO: [12] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Using AwsCandidateHarvester.
2021-05-18 09:32:32.386 INFO: [14] [hostname=xxx id=shard] MucClient.initializeConnectAndJoin#227: Initializing a new MucClient for [ org.jitsi.xmpp.mucclient.MucClientConfiguration id=shard domain=xxx hostname=xxx port=6222 username=jvb mucs=[JvbBrewery@xxx] mucNickname=xxx disableCertificateVerification=true]
2021-05-18 09:32:32.396 WARNING: [14] MucClient.createXMPPTCPConnectionConfiguration#113: Disabling certificate verification!
```

**Comment by damencho** [comment]
It is not related. 
In the past, we were printing the version as part of printing the config, and that's why my question. 
We used to print the config when starting up and that's easy for debugging problems In the community when someone sends you the log file you can check how it is running ... but it has the complication of not printing the passwords ... 
Something like the MucClientConfiguration that is printed ...

**Comment by bgrozev** [comment]
> We used to print the config when starting up and that's easy for debugging problems In the community

Yeah, that's a useful feature. Unfortunately we don't have it anymore. It would be nice to print just the values of the overriden properties, but they can now come from a variety of places -- sip-communicator.properties, jvb.conf, command line, reference.conf. And their names don't even match between sip-communicator.properties and the other sources (the code that merges them is in the files that define the properties, all over the place). Printing everything might work, but right now there's no API to do it.

As workarounds: the paths to the relevant files are included in the log, so you can ask for their contents. I've tried to add prints to places that read config values.

**Pull request merged**
