### PR TITLE
feat: Updates jitsi-stats intorducing SiteID. 

### PR DESCRIPTION
**Pull request by damencho**
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/31 and https://github.com/jitsi/jitsi-stats/pull/10

### CODE REVIEW

**Comment by damencho** [comment]
@bgrozev Did you mention you want to remove the event admin, I can do it here, I think. If I'm not mistaken the callstats was the last to use it. I was just wondering is it, possible someone, to use it in some custom additions in the bridge ...

**Comment by damencho** [comment]
The github actions failure will be red till we merge the dependent PRs and update the pom, but the PR tests should handle this.

**Comment by bbaldino** [comment]
> @bgrozev Did you mention you want to remove the event admin, I can do it here, I think. If I'm not mistaken the callstats was the last to use it. I was just wondering is it, possible someone, to use it in some custom additions in the bridge ... 

I had plans to remove it but replace it somewhat with events via a different method. I've got a branch with this for conf & ep creation/expiration

**Review by bbaldino — DISMISSED** [review]
nice! lgtm

**Review by bbaldino — APPROVED** [review]

**Pull request merged**
