### PR TITLE
move jvb source to subdir

### PR DESCRIPTION
**Pull request by bbaldino**
See https://github.com/jitsi/jitsi-videobridge/pull/1334

For now I'm just moving the source so we can get the project fixed, we can figure the rest out later.  @damencho do we still need to tweak any debian stuff?

### CODE REVIEW

**Comment by damencho** [comment]
I will test it tomorrow.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-videobridge/commits/module_fix

**Comment by damencho** [comment]
Its just easier to work on a common branch.

**Comment by damencho** [comment]
After adding my commits, deb file builds successfully. Will test it tomorrow. One thing we need to fix is the pr-tests... I wonder, maybe we need to add the PRs and pulling matching branches ...

**Comment by damencho** [comment]
Hum, I see an error that spams the logs, starts with:
```
2020-07-09 12:16:05.787 INFO: [50] [hostname=localhost id=shard] MucClient$1.connected#268: Connected.
2020-07-09 12:16:05.843 INFO: [50] [hostname=localhost id=shard] MucClient$MucWrapper.join#749: Leaving a MUC we already occupy.
2020-07-09 12:16:05.892 INFO: [50] [hostname=localhost id=shard] MucClient$MucWrapper.join#777: Joined MUC: jvbbrewery@internal.auth.meet.damencho.net
2020-07-09 12:16:10.615 INFO: [23] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$8#674: Logging in.
2020-07-09 12:16:10.616 SEVERE: [23] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.SmackException$AlreadyLoggedInException: Client is already logged in
org.jivesoftware.smack.SmackException$AlreadyLoggedInException: Client is already logged in
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwAlreadyLoggedInExceptionIfAppropriate(XMPPTCPConnection.java:371)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:487)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:448)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$8(MucClient.java:675)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
And then the `Client is already logged in` never stops ... 
Will check do I repro with the version from unstable repo

**Comment by damencho** [comment]
Why `/tmp/jvb-series.log` is enabled by default ... is this something we want?

**Comment by damencho** [comment]
The muc client error seems to be some timing issue with the errors when restarting prosody on initial install ... and is not always reproducible ... I will take a look.

**Comment by damencho** [comment]
https://github.com/jitsi/jicoco/pull/88

**Comment by damencho** [comment]
Other then those two which are now fixed and has nothing to do with the PR, the Debian package works as expected.

**Comment by bbaldino** [comment]
jenkins test this please

**Comment by bbaldino** [comment]
@damencho there were 2 more changes needed here:
1. Move `lib` dir into `jvb`, this is because it is referenced by `archive.xml` relative to `${project.basedir}`, so it should be part of the submodule I think (as opposed to doing `${project.basedir}/../lib`)
2. Move `jvb.sh` and `jvb.bat` from `./resources` to `./jvb/resources`, for the same reason as above (referred to in `archive.xml`.

If things refer to any of those files in the old location, we'll have to fix them.  Or we could use symlinks in the meantime maybe.

**Comment by damencho** [comment]
Hum, does the archive work at all? Not that is relevant to this PR ...
I see a lot of reports about that: https://community.jitsi.org/t/failed-to-build-jitsi-videobridge-from-source-code/70721?u=damencho

**Comment by damencho** [comment]
Tested jvb deb package is created, installs and works with no problem after my changes.

**Comment by bbaldino** [comment]
> Hum, does the archive work at all? Not that is relevant to this PR ...
> I see a lot of reports about that: https://community.jitsi.org/t/failed-to-build-jitsi-videobridge-from-source-code/70721?u=damencho

Pretty sure it does because it looks like the PR tests use it.

**Pull request merged**
