### PR TITLE
use maven shade plugin instead of maven assembly plugin

### PR DESCRIPTION
**Pull request by bbaldino**
Not sure this is ready yet, at this point I just want it to go through tests to see if it breaks anything there.

### CODE REVIEW

**Comment by JonathanLennox** [comment]
With this change, it looks like the file that used to be called `jitsi-videobridge-2.1-SNAPSHOT.jar` is now called `original-jitsi-videobridge-2.1-SNAPSHOT.jar`, and the former `jitsi-videobridge-2.1-SNAPSHOT-jar-with-dependencies.jar` is now `jitsi-videobridge-2.1-SNAPSHOT.jar`.  This doesn't seem like what we want?

This now no longer generates platform-specific zip files, but more than that, there's now no longer any zip file at all.  The zip files were what used to contain `jvb.sh`, `lib/logging.properties`, and `lib/videobridge.rc`.

Since we no longer generate platform-specific zip packages, we'd need to also update at least:
* The ant script (`build.xml`) - probably this should be replaced entirely?
* `make-run-test-projects.sh` in the PR testing script

**Comment by bgrozev** [comment]
The zip packages are also distributed here, though 2.0 versions are missing and I don't think anyone's complained:
https://download.jitsi.org/jitsi-videobridge/linux/

@damencho are these also used in the process of generating `.deb`s?

**Comment by damencho** [comment]
Nope, those are not used for debian packages, but I know there are many people using those.

**Comment by bbaldino** [comment]
I think for things like the zips and debian packages we should just do them separately (after the maven build).  The maven build/pom is complicated enough, and those things seem like separate, subsequent steps anyway, no?  Is there any reason they need to be part of the maven build itself?

**Comment by bbaldino** [comment]
replaced by https://github.com/jitsi/jitsi-videobridge/pull/1045

**Pull request closed without merging**
