### PR TITLE
Fix typo and indentation in bundle.md

### PR DESCRIPTION
**Pull request by xdumaine**

### CODE REVIEW

**Comment by bgrozev** [comment]
Thank you for your contribution! Before we can merge it, however we need you to sign our CLA (as [an individual](https://jitsi.org/icla) or [a corporation](https://jitsi.org/ccla)).

**Comment by SamWhited** [comment]
Do we really have to sign a CLA for a text file change? Might be worth bringing up with legal.

**Comment by xdumaine** [comment]
Signed.

**Comment by bgrozev** [comment]
Thank you!

**Pull request merged**
