### PR TITLE
deps: updates jicoco to bring in MUC XMPP port option

### PR DESCRIPTION
**Pull request by paweldomas**
Updates jicoco to 1.1-20-ge4ade96.

### CODE REVIEW

**Comment by bbaldino** [comment]
Are no other changes in the JVB itself needed?

**Comment by paweldomas** [comment]
Nope, it only reads one extra MUC config option: https://github.com/jitsi/jicoco/commit/e4ade960604368b0342cf1e629a518079ca3cff5

**Comment by paweldomas** [comment]
MUC config option are based on a prefix, so this change will read one more automatically

**Comment by bbaldino** [comment]
Ok, that's part of what I wanted to check since JVB does config differently now.  But I guess you tested with JVB and saw it works?

**Comment by paweldomas** [comment]
yes

**Pull request merged**
