### PR TITLE
set the media format of a mixed audio channel when we get the answer,

### PR DESCRIPTION
**Pull request by brianh5**
and don't force the channel to go to recvonly until it receives a packet

### CODE REVIEW

**Comment by brianh5** [comment]
first crack at this to show the general idea.  maybe a decision to be made as to how the bridge chooses the format based on the available payload types.

@emcho we talked about this a little while back, unfortunately i don't remember the details of what we agreed on, but figured this is a good enough start to get some feedback.

cc @lyubomir

**Comment by matteocampana** [comment]
Could this change make the bridge starting to send packets without waiting for the first incoming packet?

**Comment by brianh5** [comment]
@matteocampana for an audio channel that was signaled as using the mixer, yes it would cause the bridge to send before waiting to receive a packet.

**Comment by bgrozev** [comment]
Is this still relevant?

**Comment by bbaldino** [comment]
doesn't look like it

**Pull request closed without merging**
